### ISSUE TITLE
Reminders from the bot should be tuned 

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#156]
Here we could post the rules.

 - If a communication is approved: 
     - And 3 days pass without it being send. The responsible member should be notified.
     - If 7 days pass, both te member and coordination should be notified (and so forth from thereafter)

 - If a communication has an approval pending: (Attention for the new state asked, "improvements required")
     - And 3 days pass. The coordination should be notified.
     - If seven days pass, both the member and coordination should be notified and so forth.

- A communication sent should only create a notification 2 weeks after it's sent.

- A communication received should give a notification 5 days after it's received.

- It might be a good idea to allow the creation of manual reminders to avoid spam and allow time spaced conversations. For example: If a speaker asks that we remind him a month from there, or "In september". 

 - If a date is picked, a notification should be generated 5 days before, the day and then the above rules are resumed.

**Comment by JGAntunes** [comment]
Not a relevant feature right now.
