### ISSUE TITLE
Send frontend logs & errors to server

### ISSUE THREAD

**Issue by xicombd** [sinfo/eventdeck#171]
It would be cool to see the errors that people get on the browser app

**Comment by FabioAntunes** [comment]
We could use [Loggly](https://www.loggly.com/plans-and-pricing/):  

```
window.onerror = function(message, url, lineNumber) {  
  _LTracker.push({
    message: 'random error'
  })
  return true;
};  
```

More info [here](https://www.loggly.com/blog/front-end-logging-made-easy-use-this-javascript-logger/)

**Comment by JGAntunes** [comment]
I think this would be much more relevant on https://github.com/sinfo/sinfo-webapp, or on the upcoming sinfo webapp. Going to close this for now, as it wont probably be a top priority.
