### ISSUE TITLE
Scenarios that must be fulfilled

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#227]
All of these scenarios must be simple and unambiguous. 

1 - Someone from team X needs to know how something is done. How and where is that done?
2- Someone needs to post information regarding its tasks, to ask for feedback or help. Where and How?

What happens to these posts? have into account that people will leave and posts will be orphan 

3 - Someone needs to post important information regarding its team or tasks (for future reference p.e.)
How and where?

What happens to these posts?

4 - How do I know what posts have I saw? How can I know what ideas have I seen and opined, and which ones have new developments?

5 - How can I know what each team has been doing? How can I know any new developments without having to search through everything?

6 - Where and How can I find tutorials and relevant information. What if it's about a team?

7 - Where can I "store" the tasks I need to do?

**Comment by JGAntunes** [comment]
Philosophy stuff. Not relevant right now.
