### ISSUE TITLE
Add a categories field to partners (previously companies)

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#231]
e.g. this group of companies are startups.

**Comment by JGAntunes** [comment]
May be a tag system... Something to think about.

**Comment by xicombd** [comment]
How do you intend to do this? There's already the `area` field. What other groups would we have?

**Comment by JGAntunes** [comment]
Like i've said, we could have `tags` field maybe, or a `groups`. Either that or we could have another mongo collection where you could relate a group of threads. E.g. `{tag: 'startup', threads: ['topic-awesome-topic', 'company-deck', 'speaker-xico']}`

**Comment by xicombd** [comment]
The thing is, how much would this feature be used, except for the startups?

**Comment by palma21** [comment]
Well, actually, a lot if it's well done. :D

Startup
Gaming
Regular
Media
Partnership - > this is an abstraction for quite a few from the
partnerships team


Institutions or something
Student groups?

Maybe the name companies could event change for something more generic
even. Just maybe


2015-01-11 19:50 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> The thing is, how much would this feature be used, except for the startups?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/231#issuecomment-69508286>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by xicombd** [comment]
Yeah, I think we should rename the `companies` collection to `partners` or `sponsors` and then have a `kind` field which could have one of the following values:
 - `company`
 - `startup`
 - `media`
 - `partner`
 - `institution`
 - `student group`

The rest of the fields would still be the same. What do you think?

**Comment by JGAntunes** [comment]
The problem is that some of this group intersect with each other.

e.g. you could have a startup media partner.

Besides some of them might change through editions (one may be a partner
now and a sponsor next year).

**Comment by palma21** [comment]
Sounds good

Partners then. (cutting the partner category)
Might need to think on the several kinds

Transportation for example


2015-01-12 0:43 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Yeah, I think we should rename the companies collection to partners or
> sponsors and then have a kind field which could have one of the following
> values:
>
>    - company
>    - startup
>    - media
>    - partner
>    - institution
>    - student group
>
> The rest of the fields would still be the same. What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/231#issuecomment-69520234>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by palma21** [comment]
It might have more than one, such as a tag. But I don't think that is a
problem, it is regarding the use we give them. Example a media startup is a
media company for us. (no media startup will participate as a normal
startup)

2015-01-12 0:47 GMT+00:00 Jorge Palma <jorge.palma@ist.utl.pt>:

> Sounds good
>
> Partners then. (cutting the partner category)
> Might need to think on the several kinds
>
> Transportation for example
>
>
> 2015-01-12 0:43 GMT+00:00 Francisco Baio Dias <notifications@github.com>:
>
>> Yeah, I think we should rename the companies collection to partners or
>> sponsors and then have a kind field which could have one of the
>> following values:
>>
>>    - company
>>    - startup
>>    - media
>>    - partner
>>    - institution
>>    - student group
>>
>> The rest of the fields would still be the same. What do you think?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sinfo/eventdeck/issues/231#issuecomment-69520234>.
>>
>
>
>
> --
> *Jorge Palma*
> Nº 67024
> MEIC-Alameda
>
>


-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
Yeah that's what I was saying, this should work like a tag system and not
as fixed thing.

**Comment by xicombd** [comment]
Yeah, we can make it an array, how do you want to call the field? 

`kinds`, `categories`, `tags`?

**Comment by palma21** [comment]
Categories sure, as good as any :)

2015-01-12 0:53 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Yeah, we can make it an array, how do you want to call the field?
>
> kinds, categories, tags?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/231#issuecomment-69520616>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
Not a relevant feature right now.
