### ISSUE TITLE
Date must not be a mandatory field for topics (or at least for every topic)

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#234]

**Comment by xicombd** [comment]
Couldn't reproduce this bug? When/where did it happen?

**Comment by palma21** [comment]
creating topic, any topic. With no date picked

2015-01-20 0:15 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Couldn't reproduce this bug? When/where did it happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/234#issuecomment-70583753>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by xicombd** [comment]
And does that still happen?

**Comment by palma21** [comment]
yes

2015-01-20 0:25 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> And does that still happen?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/234#issuecomment-70584676>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
