### ISSUE TITLE
Delete Comment

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#236]

**Comment by xicombd** [comment]
This is already done: Edit -> Delete

**Comment by palma21** [comment]
delete button. Why do I have to edit to delete?

2015-01-20 0:16 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Closed #236 <https://github.com/sinfo/eventdeck/issues/236>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/236#event-221316110>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by xicombd** [comment]
Because why not?

**Comment by palma21** [comment]
because I want to delete not edit

2015-01-20 0:20 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Because why not?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/236#issuecomment-70584215>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
