### ISSUE TITLE
Company Layout improvement 

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#238]
There are several functionally needed layout small improvements.

Listing:
* Better area division. (History, contacts, etc). Each area should be more distinctive 
*

**Comment by JGAntunes** [comment]
Well, the layout improvement should be in all of it (the app I mean).

**Comment by palma21** [comment]
Agree. But it's functional layout improvements here. Meaning, that might
harm usability or functionality

2015-01-19 3:44 GMT+00:00 João Antunes <notifications@github.com>:

> Well, the layout improvement should be in all of it (the app I mean).
>
> On 19 January 2015 at 03:42, Jorge Palma <notifications@github.com>
> wrote:
>
> > There are several functionally needed layout small improvements.
> >
> > Listing:
> >
> > - Better area division. (History, contacts, etc). Each area should be
> > more distinctive
> > -
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sinfo/eventdeck/issues/238>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/238#issuecomment-70443207>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
Closing in favour of #324
