### ISSUE TITLE
Text that u inserted in a comment keeps showing after comment is added

### ISSUE THREAD

**Issue by Pedrovsky** [sinfo/eventdeck#244]

**Comment by Pedrovsky** [comment]
http://i.imgur.com/fB1tEcR.png

It happens in all communications maybe? 

Not urgent, later? :p

**Comment by JGAntunes** [comment]
https://github.com/AmpersandJS/ampersand-input-view#clear-inputviewclear

**Comment by JGAntunes** [comment]
@Makay11 don't use jQuery dude... Check my comment up there. Update the module and use that method.

**Comment by xicombd** [comment]
:+1: on what @JGAntunes said!

**Comment by JGAntunes** [comment]
Solved.
