### ISSUE TITLE
Some sort of unassigned tag to find companies and speakers that have no member associated.

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#247]

**Comment by xicombd** [comment]
That's implemented since ever

**Comment by palma21** [comment]
Not ever

[image: Imagem intercalada 1]

2015-01-27 2:09 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Closed #247 <https://github.com/sinfo/eventdeck/issues/247>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/247#event-225073076>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
