### ISSUE TITLE
Wrong options on Participations "Via" at Companies

### ISSUE THREAD

**Issue by nrgp** [sinfo/eventdeck#249]
Wrong options on "Via" Participations to sent invoice to companies.

![screenshot_26](https://cloud.githubusercontent.com/assets/6924254/5912396/67b3d68e-a5cb-11e4-8dda-2648c5534edd.png)

**Comment by xicombd** [comment]
What should they be?

**Comment by JGAntunes** [comment]
eheheh @nrgp thought they meant the same. Sorry @nrgp and @xicombd , when @nrgp  talked to me I didn't know what it was, in this case it's mail (physical) and email, so it's correct ;)

**Comment by nrgp** [comment]
Sorry, my fault xD
