### ISSUE TITLE
Speaker bugs

### ISSUE THREAD

**Issue by Pedrovsky** [sinfo/eventdeck#252]
Speaker Participations Give Up doesn't show:
http://i.imgur.com/7ZN8O6u.png   Visual bug?

Added a participation with the Contacted Status, no showing either:
http://i.imgur.com/kfk1dx4.png

It also happens with the give up here:
http://i.imgur.com/y5Oy1SK.png

Delete Participation worked well.

**Comment by xicombd** [comment]
Can you please confirm @Pedrovsky?

**Comment by Pedrovsky** [comment]
It seems so!
