### ISSUE TITLE
Allow CORS

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#254]
We need this for the apps.

**Comment by palma21** [comment]
Big Like

2015-01-27 15:40 GMT+00:00 João Antunes <notifications@github.com>:

> We need this for the apps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/254>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
CORS allowed on public endpoints
