### ISSUE TITLE
Emails from have pending review

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#257]

**Comment by xicombd** [comment]
That's kinda supposed, it might be confusing but *all* the communications are reviewed, mostly in two different scenarios:
 - **Email To**: When is approved, means that it can be sent 
 - **Email From** *and every other kind*: means that someone from the coordination already read the contents

Maybe what we need is another way of explaining this to the user, but this is not a bug.

Any thoughts?

**Comment by DonaGraciete** [comment]
The <b>Email From</b> should have something likea green <b>Seen</b> or <b>Read</b> instead of <b>approved!</b>, it is less confusing

**Comment by palma21** [comment]
That would work. Although, the unread feature kind of solves this (in the
eventuality of you deciding to remove it)

This is to ensure someone from the coordination sees the comm

2015-01-29 0:23 GMT+00:00 Miguel Araújo <notifications@github.com>:

> The *Email From* should have something likea green *Seen* or *Read*
> instead of *approved!*, it is less confusing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/257#issuecomment-71945712>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
Not a relevant feature right now.
