### ISSUE TITLE
To help Tank syncing, add a new field to some API requests

### ISSUE THREAD

**Issue by FabioAntunes** [sinfo/eventdeck#258]
To simplify the syncing of the Tank with event deck, instead of fetching all data and compare one by one with the local database.

I purpose adding a new optional time parameter of each request (speakers, sessions, companies, etc), when this parameter is passed I will get all the records that were update after that, if the parameter is null just returns all the records

**Comment by JGAntunes** [comment]
Not a relevant feature right now.
