### ISSUE TITLE
Issues on tables

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#259]
Some guys are experiencing stuff like this on the tables.

http://i.imgur.com/jg45pko.png

**Comment by xicombd** [comment]
That normally happens while the speakers/companies are still loading and the corrects itself.

Are those people getting stuck it that screen? If so, who are they and can we reproduce that error?

**Comment by JGAntunes** [comment]
I've tried to reproduce this on my side, without success... I think it happened to @Pedrovsky and @nrgp , both using firefox and they really got stuck in it (not loading only). Maybe we should wait for some more feedback on this. Meanwhile working on a loading scenario for everything would be cool i guess.

**Comment by palma21** [comment]
It always happens to me, without exception. Then it looks like it loads and
everything goes as it is supposed to

2015-01-29 2:18 GMT+00:00 João Antunes <notifications@github.com>:

> I've tried to reproduce this on my side, without success... I think it
> happened to @Pedrovsky <https://github.com/Pedrovsky> and @nrgp
> <https://github.com/nrgp> , both using firefox and they really got stuck
> in it (not loading only). Maybe we should wait for some more feedback on
> this. Meanwhile working on a loading scenario for everything would be cool
> i guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/259#issuecomment-71957389>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
@palma21 yes but it loads doesn't it? What we mean here is really getting stuck in this screen, nothing happens. Although @Pedrovsky had a weird issue where he couldn't fetch the companies on the front end (still waiting on feedback on this), probably related to this.

**Comment by palma21** [comment]
Probably temporary though.

It loads, but it is an odd glitch. Not a blocker though. But to be seen

2015-01-29 2:49 GMT+00:00 João Antunes <notifications@github.com>:

> @palma21 <https://github.com/palma21> yes but it loads doesn't it? What
> we mean here is really getting stuck in this screen, nothing happens.
> Although @Pedrovsky <https://github.com/Pedrovsky> had a weird issue
> where he couldn't fetch the companies on the front end (still waiting on
> feedback on this), probably related to this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/259#issuecomment-71960077>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
@franciscocgoncalves  news?

**Comment by JGAntunes** [comment]
@franciscocgoncalves ?

**Comment by JGAntunes** [comment]
Closing for the same reasons as #264.
