### ISSUE TITLE
Sometimes companies/ speakers aren't fetched

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#264]
Try opening a series of companies at once and you'll see that in some of the tabs the companies aren't fetched.

![print](http://i.imgur.com/X3X4JQw.png)

**Comment by Makay11** [comment]
I can't seem to reproduce this on localhost. Any idea why this happens?

**Comment by palma21** [comment]
It happens when you open several companies/speakers on several tabs.

No idea of the cause though



2015-02-01 15:41 GMT+00:00 Diogo Pais <notifications@github.com>:

> I can't seem to reproduce this on localhost. Any idea why this happens?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/264#issuecomment-72369654>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by palma21** [comment]
*at the same time

2015-02-01 15:43 GMT+00:00 Jorge Palma <jorge.palma@ist.utl.pt>:

> It happens when you open several companies/speakers on several tabs.
>
> No idea of the cause though
>
>
>
> 2015-02-01 15:41 GMT+00:00 Diogo Pais <notifications@github.com>:
>
>> I can't seem to reproduce this on localhost. Any idea why this happens?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sinfo/eventdeck/issues/264#issuecomment-72369654>.
>>
>
>
>
> --
> *Jorge Palma*
> Nº 67024
> MEIC-Alameda
>
>


-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by JGAntunes** [comment]
Try doing what @palma21 said. What's happens is that sometimes the app doesn't fetch the companies or the companies aren't fetched at the time of the view rendering. This issue is also related with #259 I think.

**Comment by JGAntunes** [comment]
![img](http://i.imgur.com/wkDhQe8.png)

Guys, this really needs to be resolved ASAP, it's on edit too.

**Comment by diogoleitao** [comment]
Is someone poking around with this? @JGAntunes @dmpaiva @franciscocgoncalves

**Comment by JGAntunes** [comment]
Nop, I don't think so. I'm not 100% sure but I think this may be solved
(but please do check it out). My guess is that this was an issue related
with the number of simultaneous requests we were doing per page.

João Antunes

**Comment by diogoleitao** [comment]
@JGAntunes Sometimes I don't always get all the speakers, most of the times I have to refresh the page. I think we still have some problems

**Comment by franciscocgoncalves** [comment]
@diogoleitao Does that happen to you on Speakers-> Table? If it does that's a different issue that I'll be working on this week.

**Comment by JGAntunes** [comment]
Yes, that's only supposed to happen on the tables, it should be solved on
other views (if not, we still have this issue...)

João Antunes

**Comment by diogoleitao** [comment]
On "Speakers" it doesn't but on "Members" sometimes they're not displayed alphabetically

**Comment by JGAntunes** [comment]
Yeah, that's an issue with some of the requests we have, they should be
done using the sort query param and our collections should be sorted by the
`updated` field on `companies` and `speakers` and by `name` on members per
example.

João Antunes

**Comment by JGAntunes** [comment]
@diogoleitao you were on the sort issue right?

**Comment by diogoleitao** [comment]
I'll give this one a try and if I can't come up with anything in a few days, I'll switch to #242

**Comment by JGAntunes** [comment]
This is probably related with #325, specifically the issues with the views. Will close and re-open if needed be.
