### ISSUE TITLE
Make distinction between public and private API fields

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#267]
As discussed with @palma21 confirmed speakers and closed companies should fields that clearly state that are public and are going to be accessed from the public API.

@sinfo/dev-team 
For the `company` model we already have the `history` field that should act as a private description for us, leaving the `description` field open for receiving the public content. Maybe we should only edit `description` field on public companies/ speakers (hide in the client side also)?

The remaining fields are going to be shared by both public/ private requests, being:
`title` (on speakers)
`img`
(any more?)

Although we should make people know on the client side that this fields are public and they should be careful editing them.

The other fields (like talks and such) should be on the sessions.

**Comment by palma21** [comment]
Agree. The image part is trickier now for there is no upload. For the time being I'll upload all pics to static and change the link on deck

-----Original Message-----

**Comment by JGAntunes** [comment]
Yes, on the long term we would like to support img upload.

**Comment by JGAntunes** [comment]
Summing it up:
* Add `history` field to `speaker` (don't forget db, view and route validators)
* Change names showed on the front end forms and such for something like Internal History for history and add public (in bold maybe) to all the other fields that are public (description, img, title)

**Comment by JGAntunes** [comment]
@Makay11 the history field is still missing on the speakers form
