### ISSUE TITLE
Coordinators should be subscribed to everything

### ISSUE THREAD

**Issue by Makay11** [sinfo/eventdeck#268]
Can you guys tell me if this will do it?

https://gist.github.com/Makay11/2130756b74850f7edd1e

**Comment by JGAntunes** [comment]
@Makay11 what you have to do is for every coordinator, run every speaker/company/topic and do an update with `{upsert: true}` on subscriptions collection, that will create a subscription with the thing `id` and user `id` if doesn't exist one (use also `$setOnInsert` option).

Aside from all of this you will also have to make new subscriptions on every new thread that is created. (it's easy, just put a `subscription.create` with the respective ids on the `pres` of every `create` company/speaker/topic.

**Comment by palma21** [comment]
Atention with hardcoding ids. This should work with new coordinators.

Same with permissions and such. You can do it as long as you document it for change

-----Original Message-----

**Comment by Makay11** [comment]
@palma21 There will be no hardcoded ids, I just get the coordinators from the DB in real time.

**Comment by Makay11** [comment]
@JGAntunes Did you see my Gist? I'm iterating over every company/speaker and creating a subscription for every coordinator if there isn't one already. I think it should be enough, right?

**Comment by palma21** [comment]
Hum and new ones? 
And os this done just once? And them new ones will be subscribed auto?

Sorry, on my phone

-----Original Message-----

**Comment by Makay11** [comment]
@palma21 The script I made is meant to be run once to create all the subscriptions right now. The new subscriptions will then be created when a new thread is created, like @JGAntunes said.

**Comment by palma21** [comment]
The logic sounds ok

-----Original Message-----

**Comment by Makay11** [comment]
Someone please review this commit to make sure nothing breaks:

https://github.com/sinfo/eventdeck/commit/07f0d52f76c6823129f1f6b3af9ceba18bd0c3ff
