### ISSUE TITLE
Optimize API calls

### ISSUE THREAD

**Issue by Makay11** [sinfo/eventdeck#271]
http://puu.sh/fnYQr/607faf1dca.png

This is why the browser freezes when you access the Deck.

**Comment by xicombd** [comment]
Can you try to implement pagination on the lists frontend? 

We also need to stop using `{ all: true }` on the fetches, to minimize the amount of data being transferred on each request.

**Comment by JGAntunes** [comment]
We already do it on the notifications part, we have the modules for that.

**Comment by Makay11** [comment]
More important than that is requesting only the necessary fields. That will have the biggest impact on performance.

**Comment by JGAntunes** [comment]
Issue to be sliced into more specific ones.
