### ISSUE TITLE
Mixup between comments and comms buttons, makes deleting a comment erase the comm, etc

### ISSUE THREAD

**Issue by palma21** [sinfo/eventdeck#276]

**Comment by Makay11** [comment]
Actually, the error is that the "Edit" button on a comment switches the view of the communication instead of the comment, so that when you click delete you're actually deleting the communication.

**Comment by palma21** [comment]
Possibly

2015-02-21 20:35 GMT+00:00 Diogo Pais <notifications@github.com>:

> Actually, the error is that the "Edit" button on a comment switches the
> view of the communication instead of the comment, so that when you click
> delete you're actually deleting the communication.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/276#issuecomment-75391530>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
