### ISSUE TITLE
Add opinion/feedback field to speaker

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#295]
Add a feedback field to the speaker schema that should be used for keep track of feedback given by speakers from past editions.

Implement the needed changes on the frontend also.

This requires actions on:
- mongoose models
- backend views
- frontend speaker form
- frontend speaker view

**Comment by Pedrovsky** [comment]
@diogoleitao Quando pegas nisto?

**Comment by JGAntunes** [comment]
@diogoleitao any news?

**Comment by diogoleitao** [comment]
Hoje faço isto. Eventualmente irei chatear-te (@JGAntunes) para me ajudares mas hoje vou passar o dia de volta disto. <desabafo>Já estou farto de estar sempre a adiar isto, desculpem a demora.</desabafo>

**Comment by JGAntunes** [comment]
Ok, good. I think it's the only thing missing so that we can have our
website powered by eventdeck.

João Antunes

2015-10-15 11:12 GMT+01:00 Diogo Leitão <notifications@github.com>:

**Comment by JGAntunes** [comment]
This is done right?

**Comment by diogoleitao** [comment]
Yup, you can close this
