### ISSUE TITLE
Give feedback for duped keys on creation

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#297]
We should give feedback to users on errors like duped keys. Maybe we should validate instantly as the user inserts the Name/Id.

**Comment by JGAntunes** [comment]
@dmpaiva news?

**Comment by JGAntunes** [comment]
@dmpaiva ?

**Comment by dmpaiva** [comment]
had some technical issues... this'll be done asap

**Comment by JGAntunes** [comment]
Okay. Keep me posted on this one please.

João Antunes

**Comment by JGAntunes** [comment]
@dmpaiva closed?

**Comment by dmpaiva** [comment]
I didn't know if it was good enough as it was so i left it open just in
case minor adjustments are required.

**Comment by JGAntunes** [comment]
@dmpaiva closing. If issues may come we just reopen it.
