### ISSUE TITLE
Update template

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/eventdeck#300]
Update the template used to contact speakers.

**Comment by JGAntunes** [comment]
@dmpaiva can you take care of this?

**Comment by dmpaiva** [comment]
@jgantunes, sure. Amanhã vou passar uma boa parte do dia de roda do deck, e
posso começar por estas coisas mais simples que dão jeito de ter resolvidas.

**Comment by JGAntunes** [comment]
Thanks.

**Comment by JGAntunes** [comment]
@dmpaiva any news?

**Comment by dmpaiva** [comment]
had a minor issue completing this... closed #300

**Comment by JGAntunes** [comment]
We have a new template version, can you take care of it @dmpaiva ?

**Comment by dmpaiva** [comment]
sure thing ;)

**Comment by JGAntunes** [comment]
Sent you an e-mail with the new template.

João Antunes

**Comment by JGAntunes** [comment]
@dmpaiva do me just one more favour, change the url from the Splosky photo to this one please http://sinfo.org/img/speakers/spolsky.jpg

**Comment by JGAntunes** [comment]
Done
