### ISSUE TITLE
Implement the Sessions

### ISSUE THREAD

**Issue by xicombd** [sinfo/eventdeck#37]
- nome
- data
- local
- duração
- descrição
- orador
- empresa/speaker associado

**Comment by xicombd** [comment]
Do we need comments on the sessions @palma21 @sinfo/dev-team?

**Comment by palma21** [comment]
I would say know. I think of the sessions only as a calendar or a list. Not
sure how you were viewing it.

I do think they shlould link to the session's details page. So in the case
of a keynote, it links to the speaker's page?

2015-01-22 14:43 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Do we need comments on the sessions @palma21 <https://github.com/palma21>
> @sinfo/dev-team <https://github.com/orgs/sinfo/teams/dev-team>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/37#issuecomment-71029942>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by xicombd** [comment]
No, what was planned was that the calendar links to the session details page, which can have one or more speakers associated (think of last year's CERN keynote). It can also have companies associated (for presentations/meetups/etc).

**Comment by palma21** [comment]
Ok, then. I have a different view of sessions.

No, I think it should have "Obs." but no need for comments

I see it as a final object.

For debate there are topics

2015-01-22 16:47 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> No, what was planned was that the calendar links to the session details
> page, which can have one or more speakers associated (think of last year's
> CERN keynote). It can also have companies associated (for
> presentations/meetups/etc).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/eventdeck/issues/37#issuecomment-71052602>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda

**Comment by dmpaiva** [comment]
Makes sense to me that a session has observations and not comments since
observations cover the specific aspects of a session much better than a
comment or a set of comments, plus observations are less clutter on the
session page while giving out the same information.
